CREATE DATABASE FICT_EMPRESA;
USE FICT_EMPRESA;

CREATE TABLE DEPARTAMENTOS(
	ID_DEPTO INT PRIMARY KEY NOT NULL,
	NOME_DEPTO VARCHAR(30) NOT NULL,
);

CREATE TABLE FUNCIONARIOS (
	ID_FUNC INT PRIMARY KEY NOT NULL,
	NOME_FUNC VARCHAR(60), 
	MAT_FUNC VARCHAR(5),
	ID_DEPTO INT FOREIGN KEY REFERENCES DEPARTAMENTOS(ID_DEPTO),
	CARGO VARCHAR(20)
);


INSERT INTO DEPARTAMENTOS (ID_DEPTO, NOME_DEPTO)
VALUES 
(1, 'Divisão de Informática'), 
(2, 'Engenharia'), 
(3, 'Prefeitura'), 
(4, 'Marketing'), 
(5, 'Eventos');

SELECT NOME_DEPTO FROM DEPARTAMENTOS;
